### ISSUE TITLE
Out of order RPC invocations

### ISSUE THREAD

**Issue by jspanchu** [mochi-hpc/mochi-thallium#12]
When an RPC is invoked with varying bytesized arguments, the server side invocation is out of order. I've created a minimal reproducible example at https://github.com/jspanchu/thallium-rpc-ordering/tree/main. The behavior is documented in the [README.md](https://github.com/jspanchu/thallium-rpc-ordering/blob/main/README.md) Can you please point out if we're doing something wrong in that example? Even with single rpc pool, we see this behavior.

We faced this problem in [async/async-paraview#190](https://gitlab.kitware.com/async/async-paraview/-/issues/190). I boiled it down to reproduce in the minimal example. The example uses rpc and progress pools with dedicated xstreams. Although, event with the default setup, it fails to invoke rpcs in order.

Thanks in advance!

**Comment by mdorier** [comment]
Mercury does not ensure RPC ordering. Margo/Thallium make this even worse via the use of Argobots pools and execution streams, which could take any decision regarding the order in which to execute ULTs.

In your specific case, to explain why this happens when some RPCs have large amounts of data: RPCs with small data are sent in one message. For larger data the receiving process needs a hand-shake with the sender after having reserved enough memory to actually receive the data. While this hand-shake is going on, new RPCs could be coming that will take precedence. In your case this is enabled by the `disable_response`, which makes the client not care about the response so it can immediately send the next RPCs before previous ones are executed.

**Comment by jspanchu** [comment]
I see. That explains the different order.
